### ISSUE TITLE
could this be used for online radios?

### ISSUE THREAD

**Issue by pokeball99** [CovertLizard/RadioAPI#2] opened 2015-05-05 12:03 UTC

**Comment by CovertLizard** [comment] 2015-05-06 20:54
I'm not sure what you mean... Do you mean playing midi files on websites? Or playing midi files on servers? Well if you mean playing on websites using this wouldn't make that possible, as this API was designed for minecraft clients using the Bukkit API. If you mean playing midi files on a server, that's what this whole thing does! If either of these assumptions are incorrect please try to be a bit more detailed on your question. Thanks!

**Comment by CovertLizard** [comment] 2015-05-08 22:24
If you're asking if you could play music from something like Pandora or I Heart Radio on a minecraft client, then what your asking would NOT be possible. Since you haven't replied in awhile I'm just gonna close this issue.

**Closed by CovertLizard** 2015-05-08 22:24 UTC
